# Site settings
title: Settle Gliese Developer Blog
description: > # this means to ignore newlines until "baseurl:"
  The developer blog for Settle Gliese
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.settle-gliese.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
