# Site settings
title: Blog
email: hbishop11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Another blog by another junior web developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.settle-gliese.com" # the base hostname & protocol for your site
github_username:  haggismcbean

# Build settings
markdown: kramdown
